pipeline {
    agent {
        docker {
            image 'rgonzalez01/apigee-toolset'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                dir('proxies/retail_v1') {
                    withCredentials([usernamePassword(credentialsId: 'apigee_user', passwordVariable: 'APIGEE_PASS', usernameVariable: 'APIGEE_USER')]) {
                        sh 'mvn install -Ptest -Dusername=${APIGEE_USER} -Dpassword=${APIGEE_PASS}'
                    }
                }
            }
        }
        /**
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        **/
    }
}