pipeline {
    agent {
        docker {
            image 'rgonzalez01/apigee-toolset'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                    withCredentials([usernamePassword(credentialsId: 'apigee_user', passwordVariable: 'APIGEE_PASS', usernameVariable: 'APIGEE_USER')]) {
                        sh 'cd proxies/retail_v1 && mvn install -Ptest -Dusername=${APIGEE_USER} -Dpassword=${APIGEE_PASS}'
                    }
            }
        }
    }
}