import groovy.json.JsonOutput

pipeline {
    agent {
        docker {
            image 'rgonzalez01/apigee-toolset'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Create config.json template') {
            def generated = JsonOutput.toJson(
                [
                    configurations: (
                        [
                            name:'test', proxies: (
                                [
                                    name: 'default.xml', tokens: (
                                        [xpath: '/ProxyEndpoint/HTTPProxyConnection/BasePath', value: '/retail/v1']
                                    )
                                ]
                            )
                        ]
                    )
                ]
            )
            writeJSON(file: 'proxies/retail_v1/config.json', json: generated)
        }
        stage('Build') {
            steps {
                    withCredentials([usernamePassword(credentialsId: 'apigee_user', passwordVariable: 'APIGEE_PASS', usernameVariable: 'APIGEE_USER')]) {
                        sh 'cd proxies/retail_v1 && mvn install -Ptest -Dusername=${APIGEE_USER} -Dpassword=${APIGEE_PASS}'
                    }
            }
        }
    }
}