- apt_repository: repo='deb https://apt.dockerproject.org/repo debian-jessie main'
  sudo: yes
- apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  sudo: yes
  with_items:
    - docker-engine
    - python-setuptools
- easy_install:
    name: pip
    state: latest
  sudo: yes
- pip:
    name: "{{ item }}"
  sudo: yes
  with_items:
    - requests==2.7
    - docker-py
- pip:
    name: "docker-compose"
  sudo: yes