- apt_key: keyserver='hkp://p80.pool.sks-keyservers.net:80' id='58118E89F3A912897C070ADBF76221572C52609D'
  sudo: yes
- apt_repository: repo='deb https://apt.dockerproject.org/repo debian-jessie main'
  sudo: yes
  
- apt:
    name: apt-transport-https
    state: latest
    update_cache: yes
    force: yes
  sudo: yes
  
- apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  sudo: yes
  with_items:
    - apt-transport-https
    - docker-engine
    - python-setuptools
- easy_install:
    name: pip
    state: latest
  sudo: yes
- pip:
    name: "{{ item }}"
  sudo: yes
  with_items:
    - requests==2.7
    - docker-py
- pip:
    name: "docker-compose"
  sudo: yes