- apt_key: keyserver='hkp://p80.pool.sks-keyservers.net:80' id='58118E89F3A912897C070ADBF76221572C52609D'
  sudo: yes
- apt_repository: repo='deb https://apt.dockerproject.org/repo debian-jessie main'
  sudo: yes
  
- apt:
    name: apt-transport-https
    state: latest
    force: yes
  sudo: yes
  
- apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  sudo: yes
  with_items:
    - docker-engine
    - python-setuptools
- easy_install:
    name: pip
    state: latest
  sudo: yes
- pip:
    name: "{{ item }}"
  sudo: yes
  with_items:
    - requests==2.7
    - docker-py
- pip:
    name: "docker-compose"
  sudo: yes
- file:
    path: /opt/nginx/data
    state: directory
  sudo: yes
- docker_service:
    project_name: haproxy-srv
    definition:
      version: '2'
      services:
        nginx-gen:
            image: jwilder/docker-gen
            command: -notify-sighup ${NGINX_WEB:-nginx-web} -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
            container_name: ${DOCKER_GEN:-nginx-gen}
            restart: always
            ports:
                - "${IP:-0.0.0.0}:80:80"
                - "${IP:-0.0.0.0}:443:443"
            volumes:
                - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
                - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
                - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
                - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:ro
                - /var/run/docker.sock:/tmp/docker.sock:ro
            labels:
                com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy:  "true"
        nginx-letsencrypt:
            image: jrcs/letsencrypt-nginx-proxy-companion
            container_name: ${LETS_ENCRYPT:-nginx-letsencrypt}
            restart: always
            volumes:
                - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
                - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
                - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
                - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:rw
                - /var/run/docker.sock:/var/run/docker.sock:ro
  sudo: yes