- apt_repository: repo='deb https://apt.dockerproject.org/repo debian-jessie main'
  sudo: yes
  
- name: apt-get clean
  shell: apt-get clean
  become: true
  become_user: root

- name: apt-get install
  shell: apt-get install apt-transport-https -y
  become: true
  become_user: root
  
- name: apt-get update
  shell: apt-get update
  become: true
  become_user: root
- apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  sudo: yes
  with_items:
    - apt-transport-https
    - docker-engine
    - python-setuptools
- easy_install:
    name: pip
    state: latest
  sudo: yes
- pip:
    name: "{{ item }}"
  sudo: yes
  with_items:
    - requests==2.7
    - docker-py
- pip:
    name: "docker-compose"
  sudo: yes